Update backend-deploy.yml

diff --git a/.github/workflows/backend-deploy.yml b/.github/workflows/backend-deploy.yml
--- a/.github/workflows/backend-deploy.yml
+++ b/.github/workflows/backend-deploy.yml
@@ -1,4 +1,4 @@
-name: Deploy Backend to Elastic Beanstalk
+name: Build and Publish to Elastic Beanstalk
 
 on:
   workflow_dispatch:
@@ -19,7 +19,7 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install -r requirements.txt
+          if [ -f ./chat/requirements.txt ]; then pip install -r ./chat/requirements.txt; else echo "requirements.txt not found"; exit 1; fi
 
       - name: Install AWS CLI
         run: |
